---
kind: pipeline
type: docker
name: Ubuntu | Nginx + Apache2

concurrency:
  limit: 1

platform:
  os: linux
  arch: amd64

steps:
  - name: Download submodules
    image: alpine/git
    commands:
      - git submodule update --init --recursive
  - name: Run automated testing
    image: f05be124b1e6
    commands:
      - ./test/test_helper/bats-core/install.sh /usr/local
      - ./src/hst_autocompile.sh --hestia --install '~localsrc'
      - bats ./test/test.bats
      - bats ./test/config-tests.bats

trigger:
  event: [pull_request, push]
  ref:
    - refs/heads/staging/*
    - refs/heads/beta
    - refs/heads/release
    - refs/heads/main
    - refs/pull/*/head
